const IPFS_HOST = "https://nftstorage.link/ipfs";

const products = [
  {
    id: "ctaekhpykq",
    name: "Billionare Boys Club BB Arch Long Sleeve Cotton Graphic Tee",
    description:
      "Join the club or strenthen your membership with another memorable long-sleeve from the guys at Billionaire Boys Club",
    priceInCents: 7497,
    rating: 5,
    reviewCount: 38,
    imageSrc: `${IPFS_HOST}/bafybeidhaiu3uogbkgy5dnabtoxqg6atdcmgkjy5sd5hsk6thbi3w66vla/bbc.jpg`,
    color: "white",
    category: "tees",
    sizes: "l",
    inStock: true,
  },
  {
    id: "ukdtwbmmzz",
    name: "Nike White Cotton",
    description:
      "This plain nike white tee is sure to match with a lot of items in your wardrobe while wearing one of the most recognizable logos in the world",
    priceInCents: 3997,
    rating: 5,
    reviewCount: 18,
    imageSrc: `${IPFS_HOST}/bafybeic5kvdyadhy5w22yirazhj2d4ofllfb5olbclkv7fdngtnoylwo7q/nike-white.jpg`,
    color: "white",
    category: "tees",
    sizes: "m",
    inStock: true,
  },
  {
    id: "npbnnovmko",
    name: "Adidas Original",
    description:
      "Earn and represent your stripes with an original tee from adidas",
    priceInCents: 1997,
    rating: 5,
    reviewCount: 14,
    imageSrc: `${IPFS_HOST}/bafybeifvzvh5vvkmevd4qxfnulvromg7qq4p62fah5bumyhgwuezmz2iv4/adidas.jpg`,
    color: "white",
    category: "tees",
    sizes: "l",
    inStock: true,
  },
  {
    id: "sxifbaczre",
    name: "Levis",
    description:
      "Not too many jeans out there that has your back covered like the brand Levi Strauss",
    priceInCents: 6997,
    rating: 4,
    reviewCount: 95,
    imageSrc: `${IPFS_HOST}/bafybeigcsxbtdwdz42mt3wpzin6yihk342qfb5udl5xdck5o3zy45rwo4e/levis.jpg`,
    href: "#",
    color: "blue",
    category: "pants-shorts",
    sizes: "m",
    inStock: true,
  },
  {
    id: "wvulokdgtp",
    name: "Jordan",
    priceInCents: 7997,
    description:
      "The Jordan brand is an iconic brand partnered with arguably the greatest athlete to play in all major sports",
    rating: 4,
    reviewCount: 23,
    imageSrc: `${IPFS_HOST}/bafybeib7eefltsnxnlqfoeqairbbufjksvcfxeihrjj6tiewmil5a654pq/jordan.jpg`,
    color: "grey",
    category: "sweatshirts",
    sizes: "xl",
    inStock: true,
  },
  {
    id: "ytdmxlqbmg",
    name: "Bonobos",
    priceInCents: 5498,
    description:
      "The perfect shorts for the perfect day in a nice classic beige color",
    rating: 5,
    reviewCount: 43,
    imageSrc: `${IPFS_HOST}/bafybeifrqzzkg4yllt3bkbjewmkhiyqlg4aaf7362ghdkbkxm4mh4ufuzu/bonbos.jpg`,
    color: "brown",
    category: "pant-shorts",
    sizes: "s",
    inStock: true,
  },
  {
    id: "lxvwmezdjj",
    name: "Champion",
    priceInCents: 4997,
    description:
      "Wake up feeling like a Champion with some new Champion attire",
    rating: 5,
    reviewCount: 64,
    imageSrc: `${IPFS_HOST}/bafybeie2azim5s5ls2iiiewfccyfhi2wyevgkdhwwwdgwp3rgo4q46ltnm/champion.jpg`,
    color: "green",
    category: "sweatshirts",
    sizes: "2xl",
    inStock: true,
  },
  {
    id: "kqucnmcmzk",
    name: "THe North Face",
    priceInCents: 5497,
    description:
      "Take on the outdoors with new apparel from the company with the iconic half dome logo, The North Face",
    rating: 4,
    reviewCount: 41,
    imageSrc: `${IPFS_HOST}/bafybeic2xsjavaftnxumn4acojou5whqx6cbmnisgtjinyf34ltoyfyosu/thenorthface.jpg`,
    color: "blue",
    category: "sweatshirts",
    sizes: "l",
    inStock: true,
  },
  {
    id: "dybwujsuhz",
    name: "Vuori",
    priceInCents: 6797,
    rating: 5,
    reviewCount: 35,
    imageSrc: `${IPFS_HOST}/bafybeifsi3vf6iyxdtares4dqtzi54w7fo74jrq2fi3ibzxryboq5ti6b4/vuori.jpg`,
    color: "black",
    category: "pants-shorts",
    sizes: "m",
    inStock: true,
  },
  {
    id: "zitgqknayy",
    name: "French Connection",
    description:
      "FCUK is actually based in the UK but it is an easy connection to France, match the style of the local with a new t-shirt from the French Connection",
    priceInCents: 4397,
    rating: 5,
    reviewCount: 72,
    imageSrc: `${IPFS_HOST}/bafybeihm2hyklwmmyrcupqe6fteif5cchvhj6vpygrhgcajtq7icgnmkjm/french.jpg`,
    color: "black",
    category: "tees",
    sizes: "m",
    inStock: true,
  },

  {
    id: "qizrbbgeho",
    name: "Nordstrom",
    priceInCents: 2997,
    rating: 5,
    description:
      "Nordstrom very own branded shorts based off research of selling apparel to customers, nice, versatile, and comfortable",
    reviewCount: 21,
    imageSrc: `${IPFS_HOST}/bafybeig63dcgmfcr5bfo36brhxokyyqldlxnmj6wyeofjyjl2d7zurnrca/nordstrom.jpg`,
    color: "grey",
    category: "pants-shorts",
    sizes: "xs",
    inStock: true,
  },
  {
    id: "dzwsiqjatl",
    name: "BP.",
    priceInCents: 997,
    rating: 4,
    description:
      "one can never have enough plain BP. t-shirts in their dresser, buy another and start feeling comfortable",
    reviewCount: 84,
    imageSrc: `${IPFS_HOST}/bafybeihpa2jlr2mtqk2qcy6pyxttoqoy4wjacdlnjnnp7eh64jm4z3zhpu/bp.jpg`,
    color: "blue",
    category: "tees",
    sizes: "m",
    inStock: true,
  },
];

export default products;
